# MeanSquaredError class

syntax: tf.keras.losses.MeanSquaredError(reduction="auto", name="mean_squared_error")

1. Computes the mean of squares of errors between labels and predictions.

loss = square(y_true - y_pred)

In [14]:
import tensorflow as tf

y_true = [[0.,1.], [0.,0.]]

y_pred = [[1.,1.],[1.,0.]]

mse = tf.keras.losses.MeanSquaredError(reduction="sum")

mse1 = tf.keras.losses.MeanSquaredError(reduction="sum_over_batch_size")

o1=mse(y_true, y_pred).numpy()

o2=mse1(y_true, y_pred).numpy()
 
o1

#o2

1.0

# MeanAbsoluteError class

syntax: tf.keras.losses.MeanAbsoluteError(reduction="auto", name="mean_absolute_error")

1. Computes the mean of absolute difference between labels and predictions.

loss = abs(y_true - y_pred)

In [16]:
import tensorflow as tf

y_true = [[0.,1.], [0.,0.]]

y_pred = [[1.,1.],[1.,0.]]

mse = tf.keras.losses.MeanAbsoluteError(reduction="sum")

mse1 = tf.keras.losses.MeanAbsoluteError(reduction="sum_over_batch_size")

o1=mse(y_true, y_pred).numpy()

o2=mse1(y_true, y_pred).numpy()
 
o1

o2

0.5

# MeanAbsolutePercentageError class

syntax: tf.keras.losses.MeanAbsolutePercentageError(reduction="auto", name="mean_absolute_percentage_error")

1. Computes the mean absolute percentage error between y_true and y_pred.

loss = 100 * abs(y_true - y_pred) / y_true

In [19]:


import tensorflow as tf

y_true = [[2.,1.], [2.,3.]]

y_pred = [[1.,1.],[1.,0.]]

mse = tf.keras.losses.MeanAbsolutePercentageError(reduction="sum")

mse1 = tf.keras.losses.MeanAbsolutePercentageError(reduction="sum_over_batch_size")

o1=mse(y_true, y_pred).numpy()

o2=mse1(y_true, y_pred).numpy()
 
o1

#o2

100.0

# MeanSquaredLogarithmicError class

syntax: tf.keras.losses.MeanSquaredLogarithmicError(reduction="auto", name="mean_squared_logarithmic_error")

1. Computes the mean squared logarithmic error between y_true and y_pred.

loss = square(log(y_true + 1.) - log(y_pred + 1.))

In [21]:
import tensorflow as tf

import tensorflow as tf

y_true = [[0.,1.], [0.,0.]]

y_pred = [[1.,1.],[1.,0.]]

mse = tf.keras.losses.MeanSquaredLogarithmicError(reduction="sum")

mse1 = tf.keras.losses.MeanSquaredLogarithmicError(reduction="sum_over_batch_size")

o1=mse(y_true, y_pred).numpy()

o2=mse1(y_true, y_pred).numpy()
 
o1

#o2

0.48045287

# CosineSimilarity class

syntax: tf.keras.losses.CosineSimilarity(axis=-1, reduction="auto", name="cosine_similarity")
    
    
1. Note that it is a number between -1 and 1. When it is a negative number between -1 and 0, 0 indicates orthogonality and values closer to -1 indicate greater similarity. The values closer to 1 indicate greater dissimilarity. This makes it usable as a loss function in a setting where you try to maximize the proximity between predictions and targets. If either y_true or y_pred is a zero vector, cosine similarity will be 0 regardless of the proximity between predictions and targets.

formula is gives by

loss = -sum(l2_norm(y_true) * l2_norm(y_pred))

In [8]:
import tensorflow as tf

y_true = [[0.,1.], [1.,1.]]

y_pred = [[1.,0.],[1.,1.]]

mse = tf.keras.losses.CosineSimilarity(axis=0)

mse1 = tf.keras.losses.CosineSimilarity(reduction="sum_over_batch_size")

o1=mse(y_true, y_pred).numpy()

o2=mse1(y_true, y_pred).numpy()
 
o1

#o2

0.70710677

# mean_squared_error function

syntax: tf.keras.losses.mean_squared_error(y_true, y_pred)

1. Computes the mean squared error between labels and predictions.

2. After computing the squared distance between the inputs, the mean value over the last dimension is returned.

loss = mean(square(y_true - y_pred), axis=-1)

# Returns

1. Mean squared error values. shape = [batch_size, d0, .. dN-1].

In [17]:
import tensorflow as tf

import numpy as np

y_true = np.random.randint(0,2, size=(2,3))

y_pred = np.random.random(size=(2,3))

loss = tf.keras.losses.mean_squared_error(y_true, y_pred)

loss.numpy()


array([0.32535351, 0.76704734])

# mean_absolute_error function

syntax: tf.keras.losses.mean_absolute_error(y_true, y_pred)

1. Computes the mean absolute error between labels and predictions.

loss = mean(abs(y_true - y_pred), axis=-1)

# Returns

1. Mean squared error values. shape = [batch_size, d0, .. dN-1].

In [18]:

import tensorflow as tf

import numpy as np

y_true = np.random.randint(0,2, size=(2,3))

y_pred = np.random.random(size=(2,3))

loss = tf.keras.losses.mean_absolute_error(y_true, y_pred)

loss.numpy()


array([0.45770356, 0.43356183])

# mean_absolute_percentage_error function

syntax: tf.keras.losses.mean_absolute_percentage_error(y_true, y_pred)

1. Computes the mean absolute percentage error between y_true and y_pred.

loss = 100 * mean(abs((y_true - y_pred) / y_true), axis=-1)

In [21]:
import tensorflow as tf

import numpy as np

y_true = np.random.randint(0,2, size=(2,3))

y_true = np.maximum(y_true, 1e-7)

y_pred = np.random.random(size=(2,3))

loss = tf.keras.losses.mean_absolute_percentage_error(y_true, y_pred)

loss.numpy()


array([3.32789833e+08, 3.42894185e+08])

# mean_squared_logarithmic_error function

syntax: tf.keras.losses.mean_squared_logarithmic_error(y_true, y_pred)

1. Computes the mean squared logarithmic error between y_true and y_pred.

loss = mean(square(log(y_true + 1) - log(y_pred + 1)), axis=-1)

In [25]:
import tensorflow as tf

import numpy as np

y_true = np.random.randint(0,2, size=(2,3))

y_pred = np.random.random(size=(2,3))

loss = tf.keras.losses.mean_squared_logarithmic_error(y_true, y_pred)

assert loss.shape ==(2,)

y_true = np.maximum(y_true, 1e-7)

y_pred = np.maximum(y_true, 1e-7)

loss.numpy()


array([0.12001915, 0.15088187])

# cosine_similarity function

syntax: tf.keras.losses.cosine_similarity(y_true, y_pred, axis=-1)

1. Computes the cosine similarity between labels and predictions.

loss = -sum(l2_norm(y_true) * l2_norm(y_pred))

In [28]:
import tensorflow as tf

y_true = [[0.,1.],[1.,1.],[1.,1.]]

y_pred = [[1.,0.],[1.,1.],[-1.,-1.]]

loss =tf.keras.losses.cosine_similarity(y_true, y_pred, axis=-1)

loss.numpy().tolist()

[0.0, 0.9999999403953552, -0.9999999403953552]

# Huber class

synatx: tf.keras.losses.Huber(delta=1.0, reduction="auto", name="huber_loss")

1. Computes the Huber loss between y_true and y_pred.

For each value x in error = y_true - y_pred:

loss = 0.5 * x^2                  if |x| <= d
loss = 0.5 * d^2 + d * (|x| - d)  if |x| > d

where d is delta.

In [29]:
import tensorflow as tf

y_true = [[0,1],[0,0]]

y_pred = [[0.6,0.4],[0.4,0.6]]

h = tf.keras.losses.Huber()

h(y_true, y_pred).numpy()

0.155

# huber function

syntax: tf.keras.losses.huber(y_true, y_pred, delta=1.0)

1. Computes Huber loss value.

For each value x in error = y_true - y_pred:

# LogCosh class

synatx: tf.keras.losses.LogCosh(reduction="auto", name="log_cosh")

1. Computes the logarithm of the hyperbolic cosine of the prediction error.

logcosh = log((exp(x) + exp(-x))/2), where x is the error y_pred - y_true.

In [30]:
import tensorflow as tf

y_true = [[0.,1.],[0.,0.]]

y_pred = [[1.,1.],[0.,0.]]

l = tf.keras.losses.LogCosh()

l(y_true, y_pred).numpy()

0.10844523

# log_cosh function

syntax: tf.keras.losses.log_cosh(y_true, y_pred)

1. Logarithm of the hyperbolic cosine of the prediction error.

log(cosh(x)) is approximately equal to (x ** 2) / 2 for small x 

and to abs(x) - log(2) for large x. 

2. This means that 'logcosh' works mostly like the mean squared error, but will not be so strongly affected by the occasional wildly incorrect prediction.

In [ ]:
import numpy as np

y_true = np.random.random(size=(2, 3))
y_pred = np.random.random(size=(2, 3))
loss = tf.keras.losses.logcosh(y_true, y_pred)
assert loss.shape == (2,)
x = y_pred - y_true