In [10]:
#Activations
#Activation is a layer 
#it can be used as an argument inside the layers


import keras
import tensorflow as tf
#import numpy as np

model = tf.keras.Sequential()

#model.add(tf.keras.layers.Dense(10, activation=tf.keras.activations.relu))

model.add(tf.keras.layers.Dense(10, activation='relu')) #activation as argument
model.add(tf.keras.layers.Activation(activation='relu')) #using the activation as an independent layer

In [27]:
#RELU
#rectified linear unit activn fn
#logic max(x,0) where X is the input tensor
#This function returns the maximum among the input tensor or 0 when applied.
#it is used to maintain the value above a certain threshold


#tf.keras.activations.relu(x, alpha, threshold, max_value)

#x is the input [tensor]
#alpha controls the slope [float]
#max_value sets the largest value the function can return [float]
#threshold sets the threshold value below which all the values are zero or damped[float]


f = tf.constant([-10, -5, -4, -2], dtype=tf.float32)
out = tf.keras.activations.relu(f)
out.numpy()

out1 = tf.keras.activations.relu(f, threshold=-5)
out1.numpy()

array([-0., -0., -4., -2.], dtype=float32)

In [37]:
#sigmoid function
#tf.keras.activations.sigmoid(x)

#sigmoid(x) = 1 / (1 + exp(-x)).
#for values(<-5) sigmoid returns and for values(>5) sigmoid returns values close to 1.
#sigmoid always returns a value between

a = tf.constant([-20.0,-10.0,0.0,1.0,2.0], dtype=tf.float32)
b = tf.keras.activations.sigmoid(a)
b.numpy()


array([2.0611537e-09, 4.5397872e-05, 5.0000000e-01, 7.3105860e-01,
       8.8079703e-01], dtype=float32)

In [44]:
#softmax 
#converts real vectors to the veactors of the categoricala probabilities 
#each output is in the range of (0,1)
#softmax is often used as the activation for the last layer of a classification network.

#tf.keras.activations.softmax(x, axis=-1)

#example 
import tensorflow as tf
from math import exp
out = exp(2)/ tf.reduce_sum(exp(2))

out.numpy()

1.0

In [62]:
#softplus
#tf.keras.activations.softplus(x)
#softplus(x) = log(exp(x)+1)


x = tf.constant([-10.0,2.0,3.0], dtype=tf.float32)
out = tf.keras.activations.softplus(x)
out.numpy()

array([4.5417706e-05, 2.1269281e+00, 3.0485873e+00], dtype=float32)

In [64]:
#softsign function
#tf.keras.activations.softsign(x)

#softsign = x/(abs(x)+1)

x = tf.constant([-20.0,-10.0,-6.0,5.0,4.0], dtype=tf.float32)
out = tf.keras.activations.softsign(x)
out

<tf.Tensor: id=154, shape=(5,), dtype=float32, numpy=
array([-0.95238096, -0.90909094, -0.85714287,  0.8333333 ,  0.8       ],
      dtype=float32)>

In [71]:
#tanh function
#tf.keras.activations.tanh(x)
#it is a hyperbolic tangent function

#sinh(x)/ cosh(x) = exp(x)-exp(-x)/exp(x)+exp(-x)

x = tf.constant([-20.0,-10.0,-6.0,5.0,4.0], dtype=tf.float32)
out = tf.keras.activations.tanh(x)
out.numpy()


array([-1.        , -1.        , -0.99998784,  0.99990916,  0.9993292 ],
      dtype=float32)

In [72]:
#selu function
#tf.keras.activations.selu(x)
#scaled exponential linear unit
#logic 
"""
if x > 0: it returns sclae*x
if x < 0: it returns scale*alpha*(exp(x)-1)

where alpha = 1.67326324 and scale = 1.05070098

"""
#SELU multiplies scale with the output of the ELU to ensure the slope is larger than one of the positive inputs

#The scaled exponential unit activation: scale * elu(x, alpha).

#Notes: - To be used together with the tf.keras.initializers.LecunNormal initializer. - To be used together with the dropout variant tf.keras.layers.AlphaDropout (not regular dropout).

'\nif x > 0: it returns sclae*x\nif x < 0: it returns scale*alpha*(exp(x)-1)\n\nwhere alpha = 1.67326324 and scale = 1.05070098\n\n'

In [73]:
#elu 
#exponential linear unit
"""
if x > 0 and alpha > 0: x
if x < 0 then x:alpha * (exp(x)-1)

where alpha is a hyperparameter that controls that values used by alpha for saturating the negative inputs
"""

#ELU solves the vanishing gradient problem
#ELU reduces the variation by bringing the gradient closer to the natural gradient
#when the variation is diminished, the learning is faster

'\nif x > 0 and alpha > 0: x\nif x < 0 then x:alpha * (exp(x)-1)\n\nwhere alpha is a hyperparameter that controls that values used by alpha for saturating the negative inputs\n'

In [77]:
#exponential function
#tf.keras.activations.exponential(x)

x=a
b = tf.keras.activations.exponential(a)
b.numpy()


array([2.0611537e-09, 4.5399931e-05, 2.4787523e-03, 1.4841316e+02,
       5.4598148e+01], dtype=float32)