In [19]:
#Concatenate layer
#method

import tensorflow as tf
import numpy as np
tf.keras.layers.Concatenate(axis=-1)

#this concatenates all the tensors it receives as input into a single tensor. All tensors have same shape except the concatenation axis.

#examples

x = np.arange(20).reshape(2,2,5)
print(x)

y = np.arange(20, 30).reshape(2,1,5)
print(y)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[20 21 22 23 24]]

 [[25 26 27 28 29]]]


In [20]:
tf.keras.layers.Concatenate(axis=1)([x,y])



<tf.Tensor: id=4, shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]]])>

In [24]:
#concatenating two layers

x1 = tf.keras.layers.Dense(8)(np.arange(10, dtype=np.float32).reshape(5,2))

x2 = tf.keras.layers.Dense(8)(np.arange(10,20, dtype= np.float32).reshape(5,2))

concatted = tf.keras.layers.Concatenate()([x1, x2])

concatted.shape

TensorShape([5, 16])

In [32]:
#Average layer

#method
tf.keras.layers.Average()

#this layer averages a list of input tensors

#examples

x1=np.ones((2,2))

x2=np.zeros((2,2))

y = tf.keras.layers.Average()([x1,x2])

y.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]

In [33]:
#maximum 

tf.keras.layers.Maximum()

#Layer that computes the maximum (element-wise) a list of inputs.

tf.keras.layers.Maximum()([np.arange(5).reshape(5,1), np.arange(5,10).reshape(5,1)])



<tf.Tensor: id=135, shape=(5, 1), dtype=int64, numpy=
array([[5],
       [6],
       [7],
       [8],
       [9]])>

In [34]:
#minimum 

tf.keras.layers.Minimum()

#Layer that computes the minimum (element-wise) a list of inputs.

tf.keras.layers.Minimum()([np.arange(5).reshape(5,1), np.arange(5,10).reshape(5,1)])

<tf.Tensor: id=139, shape=(5, 1), dtype=int64, numpy=
array([[0],
       [1],
       [2],
       [3],
       [4]])>

In [45]:
#add

tf.keras.layers.Add()

#this layer adds a list of inputs

input_shape = (2,3,4)

x1= tf.random.normal(input_shape)

x2= tf.random.normal(input_shape)

y = tf.keras.layers.Add()([x1, x2])

print(y)



print(y.shape)

tf.Tensor(
[[[ 0.3501898   0.64183414 -0.01137942 -2.322097  ]
  [ 0.50621516 -1.1376328  -0.4489379  -0.8646163 ]
  [-0.8479014   0.77535176 -1.1206237  -1.1515749 ]]

 [[-0.52113247  0.60995805  2.7456508  -1.1865522 ]
  [-1.01085    -2.5956163  -0.02192307  1.1554599 ]
  [ 1.3221468  -1.4113002  -2.1390765  -1.3381321 ]]], shape=(2, 3, 4), dtype=float32)
(2, 3, 4)


In [48]:
#subtract
#It takes as input a list of tensors of size 2, both of the same shape, and returns a single tensor, (inputs[0] - inputs[1]), also of the same shape.

tf.keras.layers.Subtract()

#this layer adds a list of inputs

input_shape = (2,3,4)

x1= tf.random.normal(input_shape)

x2= tf.random.normal(input_shape)

y = tf.keras.layers.Subtract()([x1, x2])

print(y)


print(y.shape)

tf.Tensor(
[[[ 1.2112538   0.67446566 -2.5346925  -1.7515049 ]
  [ 1.8488966   3.1246588  -0.01496531  1.2114878 ]
  [-3.45125     1.3030977   1.7980235   0.5965969 ]]

 [[ 1.5527847  -1.5846543  -0.15682012 -0.44893402]
  [-0.72632515 -1.0324135  -0.17921448  1.4872167 ]
  [-3.0548682   1.7272077   1.4765021   1.6520807 ]]], shape=(2, 3, 4), dtype=float32)
(2, 3, 4)


In [49]:
#multiply
#It takes as input a list of tensors of size 2, both of the same shape, and returns a single tensor, (inputs[0] - inputs[1]), also of the same shape.

tf.keras.layers.Multiply()

#this layer adds a list of inputs

input_shape = (2,3,4)

x1= tf.random.normal(input_shape)

x2= tf.random.normal(input_shape)

y = tf.keras.layers.Multiply()([x1, x2])

print(y)


print(y.shape)

tf.Tensor(
[[[ 6.3286647e-02  2.0197420e+00  3.3912897e-01 -5.4825377e-01]
  [ 1.1433582e-01  7.5813311e-01 -7.9880297e-01 -7.6574370e-02]
  [-7.3313272e-01 -3.8183281e-01  7.7997053e-01  6.5150201e-01]]

 [[ 8.0015761e-01 -5.3068640e-04  3.3628875e-01  1.3814387e+00]
  [ 8.3360267e-01 -1.6078916e+00 -5.6708292e-03  1.9228290e-01]
  [ 6.9761056e-01 -4.9298251e-01  2.0696257e-01  9.0579860e-02]]], shape=(2, 3, 4), dtype=float32)
(2, 3, 4)


In [64]:
#dot product

tf.keras.layers.Dot(axes=0, normalize=False)

input_shape = (2,2)

x1= tf.random.normal(input_shape)

x2= tf.random.normal(input_shape)

y = tf.keras.layers.Dot(axes=1)([x1, x2])




print(y)

print(y.shape)





tf.Tensor(
[[0.09837128]
 [0.1584119 ]], shape=(2, 1), dtype=float32)
(2, 1)
