In [1]:
#Reshape
#method

tf.keras.layers.Reshape(target_shape)

#this reshapes the input into the target shape

#input shape 
"""
Arbitrary, although all dimensions in the input shape must be known/fixed. Use the keyword argument input_shape (tuple of integers, does not include the samples/batch size axis) when using this layer as the first layer in a model.

"""

#output shape

"""
(batch_size, ) + target_shape

"""
#example
#used as first layer in a model
import tensorflow as tf
model = tf.keras.Sequential()
model.add(tf.keras.layers.Reshape((12,), input_shape=(12,)))
model.output_shape

#as intermediate layer

model.add(tf.keras.layers.Reshape(target_shape=(6,2)))

model.output_shape


NameError: name 'tf' is not defined

In [2]:
#flatten layer
#this layer flattens the input but doesn't affect the batch_size
#flattening layer converts the output of CNN into feature vectors to be used by the ANN
#method

tf.keras.layers.Flatten(data_format=None)

# If inputs are shaped (batch,) without a feature axis, then flattening adds an extra channel dimension and output shape is (batch, 1).

#Arguments

"""
data_format - A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch, ..., channels) while channels_first corresponds to inputs with shape (batch, channels, ...). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""

#example

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(64,3,3, input_shape=(3,32,32)))

out1 = model.output_shape

model.add(tf.keras.layers.Flatten())

out2 = model.output_shape


print(out1)

out2

NameError: name 'tf' is not defined

In [3]:
#RepeatVector
tf.keras.layers.RepeatVector(n)

#repeats the input n times

#example
model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(32, input_dim=32))

model.add(tf.keras.layers.RepeatVector(3))

#input shape
"""
2D tensor of shape (num_samples, features)

"""

#output shape
"""
3D tensor of shape (num_samples, n, features)
"""

NameError: name 'tf' is not defined

In [4]:
#permute
tf.keras.layers.Permute(dims=(1,2))

#permutes the dimension of the input according to a given pattern

#example
model = tf.keras.Sequential()

model.add(tf.keras.Permute(2,1), input_shape=(10, 64))

"""
output = (None, 64, 10)

"""

#arguments
"""
dims = [tuple of integers]Permutation pattern does not include the samples dimension. Indexing starts at 1. For instance, (2, 1) permutes the first and second dimensions of the input.

"""

#Input shape

#Arbitrary. Use the keyword argument input_shape (tuple of integers, does not include the samples axis) when using this layer as the first layer in a model.

#Output shape

#Same as the input shape, but with the dimensions re-ordered according to the specified pattern.

NameError: name 'tf' is not defined

In [29]:
#cropping1D
import tensorflow as tf

import numpy as np
tf.keras.layers.Cropping1D(cropping=(1,1))

input_shape = (2,3,2)
x= np.arange(np.prod(input_shape)).reshape(input_shape)

x

y = tf.keras.layers.Cropping1D(cropping=(2,0))(x)

y

#arguments
"""
cropping - int or tuple of int(length 2) How many units should be trimmed off at the beginning and the end of the cropping dimension(axis1)

"""

#input shape

"""

3D tensor with shape (batch_size, axis_to_crop, features)

"""

#output_shape 

"""
3D tensor with shape (batch_size, cropped_axis, features)

"""

'\n3D tensor with shape (batch_size, cropped_axis, features)\n\n'

In [19]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [38]:
#Cropping2D class

tf.keras.layers.Cropping2D(cropping=((0, 0), (0, 0)), data_format=None)

#this crops along the spatial dimensions i.e. height and width


input_shape = (2, 28, 28, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)

print(x)
y = tf.keras.layers.Cropping2D(cropping=((2, 2), (4, 4)))(x)
print(y.shape)


#ARGUMENTS

"""
cropping- 

Int, or tuple of 2 ints, or tuple of 2 tuples of 2 ints.

    If int: the same symmetric cropping is applied to height and width.
    If tuple of 2 ints: interpreted as two different symmetric cropping values for height and width: (symmetric_height_crop, symmetric_width_crop).
    If tuple of 2 tuples of 2 ints: interpreted as ((top_crop, bottom_crop), (left_crop, right_crop))

data_format - 

    A string, one of channels_last (default) or channels_first. 
    
    The ordering of the dimensions in the inputs. 
    
    channels_last corresponds to inputs with shape (batch_size, height, width, channels) 
    
    
    while channels_first corresponds to inputs with shape (batch_size, channels, height, width). 
    
    
    It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""

#Input shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, rows, cols, channels) - If data_format is "channels_first": (batch_size, channels, rows, cols)
"""


#Output shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, cropped_rows, cropped_cols, channels) - If data_format is "channels_first": (batch_size, channels, cropped_rows, cropped_cols)
"""

[[[[   0    1    2]
   [   3    4    5]
   [   6    7    8]
   ...
   [  75   76   77]
   [  78   79   80]
   [  81   82   83]]

  [[  84   85   86]
   [  87   88   89]
   [  90   91   92]
   ...
   [ 159  160  161]
   [ 162  163  164]
   [ 165  166  167]]

  [[ 168  169  170]
   [ 171  172  173]
   [ 174  175  176]
   ...
   [ 243  244  245]
   [ 246  247  248]
   [ 249  250  251]]

  ...

  [[2100 2101 2102]
   [2103 2104 2105]
   [2106 2107 2108]
   ...
   [2175 2176 2177]
   [2178 2179 2180]
   [2181 2182 2183]]

  [[2184 2185 2186]
   [2187 2188 2189]
   [2190 2191 2192]
   ...
   [2259 2260 2261]
   [2262 2263 2264]
   [2265 2266 2267]]

  [[2268 2269 2270]
   [2271 2272 2273]
   [2274 2275 2276]
   ...
   [2343 2344 2345]
   [2346 2347 2348]
   [2349 2350 2351]]]


 [[[2352 2353 2354]
   [2355 2356 2357]
   [2358 2359 2360]
   ...
   [2427 2428 2429]
   [2430 2431 2432]
   [2433 2434 2435]]

  [[2436 2437 2438]
   [2439 2440 2441]
   [2442 2443 2444]
   ...
   [2511 2512 2513]
 

'\n4D tensor with shape: - If data_format is "channels_last": (batch_size, cropped_rows, cropped_cols, channels) - If data_format is "channels_first": (batch_size, channels, cropped_rows, cropped_cols)\n'

In [ ]:
#cropping3D 

#method

tf.keras.layers.Cropping3D(cropping=((1,1),(1,1),(1,1)), data_format=None)

#spatio-temporal cropping

#arguments

"""

cropping: Int, or tuple of 3 ints, or tuple of 3 tuples of 2 ints.
        
        If int: the same symmetric cropping is applied to depth, height, and width.
        
        If tuple of 3 ints: interpreted as two different symmetric cropping values for depth, height, and width: (symmetric_dim1_crop, symmetric_dim2_crop, symmetric_dim3_crop).
        
        If tuple of 3 tuples of 2 ints: interpreted as ((left_dim1_crop, right_dim1_crop), (left_dim2_crop, right_dim2_crop), (left_dim3_crop, right_dim3_crop))
    
    
data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch_size, spatial_dim1, spatial_dim2, spatial_dim3, channels) while channels_first corresponds to inputs with shape (batch_size, channels, spatial_dim1, spatial_dim2, spatial_dim3). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""

#Input shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, first_axis_to_crop, second_axis_to_crop, third_axis_to_crop, depth) - If data_format is "channels_first": (batch_size, depth, first_axis_to_crop, second_axis_to_crop, third_axis_to_crop)
"""


#Output shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, first_cropped_axis, second_cropped_axis, third_cropped_axis, depth) - If data_format is "channels_first": (batch_size, depth, first_cropped_axis, second_cropped_axis, third_cropped_axis)
"""


In [44]:
#Upsampling

#method 
tf.keras.layers.UpSampling1D(size=2)

input_shape= (4,1,2)

x = np.arange(np.prod(input_shape)).reshape(input_shape)

out = x
print(out)

y = tf.keras.layers.UpSampling1D(size=2)(x)

y

#arguments

"""
size: [int] this argument is upsampling factor
"""

#input shape
"""
3D tensor with shape: (batch_size, steps, features).

"""

#output shape

"""
3D tensor with shape: (batch_size, upsampled_steps, features).

"""


[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]]


<tf.Tensor: id=121, shape=(4, 2, 2), dtype=int64, numpy=
array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]]])>

In [ ]:
#upsampling2D

#method

tf.keras.layers.UpSampling2D(size=(2, 2), data_format=None, interpolation="nearest", **kwargs)

#Repeats the rows and columns of the data by size[0] and size[1] respectively.

#arguments
"""
size: Int, or tuple of 2 integers. The upsampling factors for rows and columns.
    
data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch_size, height, width, channels) while channels_first corresponds to inputs with shape (batch_size, channels, height, width). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".
    
interpolation: A string, one of nearest or bilinear.
"""

#Input shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, rows, cols, channels) - If data_format is "channels_first": (batch_size, channels, rows, cols)
"""
#Output shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, upsampled_rows, upsampled_cols, channels) - If data_format is "channels_first": (batch_size, channels, upsampled_rows, upsampled_cols)

"""

In [45]:
#UpSampling3D class

tf.keras.layers.UpSampling3D(size=(2, 2, 2), data_format=None, **kwargs)

#Upsampling layer for 3D inputs.

#Repeats the 1st, 2nd and 3rd dimensions of the data by size[0], size[1] and size[2] respectively.

#arguments
"""

size: Int, or tuple of 3 integers. The upsampling factors for dim1, dim2 and dim3.
    
data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch_size, spatial_dim1, spatial_dim2, spatial_dim3, channels) while channels_first corresponds to inputs with shape (batch_size, channels, spatial_dim1, spatial_dim2, spatial_dim3). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""

#Input shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, dim1, dim2, dim3, channels) - If data_format is "channels_first": (batch_size, channels, dim1, dim2, dim3)
"""
#Output shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, upsampled_dim1, upsampled_dim2, upsampled_dim3, channels) - If data_format is "channels_first": (batch_size, channels, upsampled_dim1, upsampled_dim2, upsampled_dim3)
"""

NameError: name 'kwargs' is not defined

In [ ]:
#zero_padding1D

tf.keras.layers.ZeroPadding1D(padding=1, **kwargs)

#Arguments
"""
padding: Int, or tuple of int (length 2), or dictionary. - If int: How many zeros to add at the beginning and end of the padding dimension (axis 1). - If tuple of int (length 2): How many zeros to add at the beginning and the end of the padding dimension ((left_pad, right_pad)).
"""

#Input shape
"""
3D tensor with shape (batch_size, axis_to_pad, features)
"""

#Output shape
"""
3D tensor with shape (batch_size, padded_axis, features)
"""

In [ ]:
#ZeroPadding2D class

tf.keras.layers.ZeroPadding2D(padding=(1, 1), data_format=None, **kwargs)

Zero-padding layer for 2D input (e.g. picture).

#This layer can add rows and columns of zeros at the top, bottom, left and right side of an image tensor.

#Arguments
"""
padding: Int, or tuple of 2 ints, or tuple of 2 tuples of 2 ints.
        
If int: the same symmetric padding is applied to height and width.
        
If tuple of 2 ints: interpreted as two different symmetric padding values for height and width: (symmetric_height_pad, symmetric_width_pad).
        
If tuple of 2 tuples of 2 ints: interpreted as ((top_pad, bottom_pad), (left_pad, right_pad))
    
data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch_size, height, width, channels) while channels_first corresponds to inputs with shape (batch_size, channels, height, width). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""

#Input shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, rows, cols, channels) - If data_format is "channels_first": (batch_size, channels, rows, cols)
"""

#Output shape
"""
4D tensor with shape: - If data_format is "channels_last": (batch_size, padded_rows, padded_cols, channels) - If data_format is "channels_first": (batch_size, channels, padded_rows, padded_cols)
"""

In [ ]:
Z#eroPadding3D layer


tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1), data_format=None, **kwargs)

#Zero-padding layer for 3D data (spatial or spatio-temporal).


#Arguments
"""
padding: Int, or tuple of 3 ints, or tuple of 3 tuples of 2 ints.
        
If int: the same symmetric padding is applied to height and width.
        
If tuple of 3 ints: interpreted as two different symmetric padding values for height and width: (symmetric_dim1_pad, symmetric_dim2_pad, symmetric_dim3_pad).
        
If tuple of 3 tuples of 2 ints: interpreted as ((left_dim1_pad, right_dim1_pad), (left_dim2_pad, right_dim2_pad), (left_dim3_pad, right_dim3_pad))
    
data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape (batch_size, spatial_dim1, spatial_dim2, spatial_dim3, channels) while channels_first corresponds to inputs with shape (batch_size, channels, spatial_dim1, spatial_dim2, spatial_dim3). It defaults to the image_data_format value found in your Keras config file at ~/.keras/keras.json. If you never set it, then it will be "channels_last".

"""
#Input shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, first_axis_to_pad, second_axis_to_pad, third_axis_to_pad, depth) - If data_format is "channels_first": (batch_size, depth, first_axis_to_pad, second_axis_to_pad, third_axis_to_pad)
"""

#Output shape
"""
5D tensor with shape: - If data_format is "channels_last": (batch_size, first_padded_axis, second_padded_axis, third_axis_to_pad, depth) - If data_format is "channels_first": (batch_size, depth, first_padded_axis, second_padded_axis, third_axis_to_pad
"""