In [2]:
#dropout class
#method 
tf.keras.layers.Dropout(rate, noise_shape=None, seed=None)

#this randomly sets input units to 0 with a frequency of rate at each step during the training time. which helps prevent overfitting.
#inputs not set to zero are multiplied by a factor of 1/(1-rate)

#dropout layer only applies when the parameter training =True so that the values are only dropped when training takes place and not during the inference mode.

#This is in contrast to setting trainable=False for a Dropout layer. trainable does not affect the layer's behavior, as Dropout does not have any variables/weights that can be frozen during training.

#arguments
"""
rate: [float]. metric to set the rate at which the input units are to be dropped.

noise_shape: 1D integer representing the shape of the mask that is to be multiplied by the input. 

seed: a python [integer] to use as random seed.

"""

#call arguments

"""
1. input: tensor of any rank

2. training:  Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

"""



NameError: name 'tf' is not defined

In [21]:
import tensorflow as tf

import numpy as np

tf.random.set_seed(0)

layer = tf.keras.layers.Dropout(0.51, input_shape=(2,))
data = np.arange(10).reshape(2,5,1).astype(np.float32)
print(data)

out = layer(data, training=True)
out

[[[0.]
  [1.]
  [2.]
  [3.]
  [4.]]

 [[5.]
  [6.]
  [7.]
  [8.]
  [9.]]]


<tf.Tensor: id=43, shape=(2, 5, 1), dtype=float32, numpy=
array([[[ 0.       ],
        [ 0.       ],
        [ 4.0816326],
        [ 6.122449 ],
        [ 0.       ]],

       [[10.204082 ],
        [ 0.       ],
        [14.285714 ],
        [16.32653  ],
        [ 0.       ]]], dtype=float32)>

In [23]:
#spatialdropout
#method 
tf.keras.layers.SpatialDropout1D(rate)

#This version performs the similar function, but, it froprs the entire 1D feature maps instead of in
# If adjacent frames within feature maps are strongly correlated (as is normally the case in early convolution layers) then regular dropout will not regularize the activations and will otherwise just result in an effective learning rate decrease. In this case, SpatialDropout1D will help promote independence between feature maps and should be used instead.

#Arguments

#rate: Float between 0 and 1. Fraction of the input units to drop.

#Call arguments

#inputs: A 3D tensor.
#training: Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

#Input shape

#3D tensor with shape: (samples, timesteps, channels)

#Output shape

#Same as input.


NameError: name 'rate' is not defined

In [26]:
#spatialDropout2D
tf.keras.layers.SpatialDropout2D(rate, data_format=None)

#this eliminates entire 2D feature maps instead of individual elements.

#call arguments 
"""
inputs: 4D tensor

training: [boolean] whether the layer should run in training or inference mode.

"""

#input shape

#4D tensor with shape: (samples, channels, rows, cols) if data_format='channels_first' or 4D tensor with shape: (samples, rows, cols, channels) if data_format='channels_last'.

#output shape

#same as input

'\ninputs: 4D tensor\n\ntraining: [boolean] whether the layer should run in training or inference mode.\n\n'

In [27]:
#spatialDropout2D
tf.keras.layers.SpatialDropout3D(rate, data_format=None)

#this eliminates entire 3D feature maps instead of individual elements.

#call arguments 
"""
inputs: 5D tensor

training: [boolean] whether the layer should run in training or inference mode.

"""

#input shape

#5D tensor with shape: (samples, channels, dim1, dim2, dim3) if data_format='channels_first' or 5D tensor with shape: (samples, dim1, dim2, dim3, channels) if data_format='channels_last'.

#output shape

#same as input


NameError: name 'rate' is not defined

In [28]:
#gaussianDropout

#method

tf.keras.layers.GaussianDropout(rate)

#this layer applies 1-centered gaussian noise

#its only active during training time

#arguments

"""
rate: [float] drop probability. the multiplicative noise will have standard deviation sqrt(rate/ (1-rate))

"""

#call arguments

"""
1. input: tensor of any rank

2. training:  Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

"""

#Input shape

#Arbitrary. Use the keyword argument input_shape (tuple of integers, does not include the samples axis) when using this layer as the first layer in a model.

#Output shape

#Same shape as input.

NameError: name 'rate' is not defined

In [29]:
#GaussianNoise 

#method

tf.keras.layers.GaussianNoise(stddev)

#apply additive zero-centered Gaussian noise

#This is useful to mitigate overfitting (you could see it as a form of random data augmentation). Gaussian Noise (GS) is a natural choice as corruption process for real valued inputs.

#arguments

"""
stddev : [float] stddev of the noise distribution
"""


#call arguments

"""
1. input: tensor of any rank

2. training:  Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

"""

#Input shape

#Arbitrary. Use the keyword argument input_shape (tuple of integers, does not include the samples axis) when using this layer as the first layer in a model.

#Output shape

#Same shape as input.

NameError: name 'stddev' is not defined

In [30]:
#activityregularization 

#method
tf.keras.layers.ActivityRegularization(l1=0.0, l2=0.0)

#Layer that applies an update to the cost function based input activity.

#Arguments
"""
    l1: L1 regularization factor (positive float).
    l2: L2 regularization factor (positive float).
"""
#call arguments

"""
1. input: tensor of any rank

2. training:  Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

"""

#Input shape

#Arbitrary. Use the keyword argument input_shape (tuple of integers, does not include the samples axis) when using this layer as the first layer in a model.

#Output shape

#Same shape as input.

'\n    l1: L1 regularization factor (positive float).\n    l2: L2 regularization factor (positive float).\n'

In [ ]:
#alphaDropout 

tf.keras.layers.AlphaDropout(rate, noise_shape=None, seed=None)

#Alpha Dropout is a Dropout that keeps mean and variance of inputs to their original values, in order to ensure the self-normalizing property even after this dropout. Alpha Dropout fits well to Scaled Exponential Linear Units by randomly setting activations to the negative saturation value.

#arguments

"""

    rate: float, drop probability (as with Dropout). The multiplicative noise will have standard deviation sqrt(rate / (1 - rate)).
    seed: A Python integer to use as random seed.


"""

#call arguments

"""
1. input: tensor of any rank

2. training:  Python boolean indicating whether the layer should behave in training mode (adding dropout) or in inference mode (doing nothing).

"""

#Input shape

#Arbitrary. Use the keyword argument input_shape (tuple of integers, does not include the samples axis) when using this layer as the first layer in a model.

#Output shape

#Same shape as input.